import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { PhysArchGeneratedModule, PhysArchGeneratedSharedModule } from './generated/module';
import { PhysArchValidator, registerValidationChecks } from './phys-arch-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type PhysArchAddedServices = {
    validation: {
        PhysArchValidator: PhysArchValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type PhysArchServices = LangiumServices & PhysArchAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const PhysArchModule: Module<PhysArchServices, PartialLangiumServices & PhysArchAddedServices> = {
    validation: {
        PhysArchValidator: () => new PhysArchValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createPhysArchServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    PhysArch: PhysArchServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        PhysArchGeneratedSharedModule
    );
    const PhysArch = inject(
        createDefaultModule({ shared }),
        PhysArchGeneratedModule,
        PhysArchModule
    );
    shared.ServiceRegistry.register(PhysArch);
    registerValidationChecks(PhysArch);
    return { shared, PhysArch };
}
